spring.application.name=Asgard

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.sql.init.schema-locations=optional:classpath:sql/schema.sql
spring.sql.init.data-locations=optional:classpath:sql/data.sql

bot.display-name=${BOT_QUERY_NAME}
bot.password=${BOT_QUERY_PASS}
bot.host=${BOT_SERVER_HOST}
bot.port=${BOT_SERVER_PORT}
bot.username=${BOT_USERNAME}

bot.service.base-url=${BOT_SERVICE_BASE_URL:http://heimdall:5000}

jwt.secret=${JWT_SECRET:542ba18b-7a80-47cd-9550-839f238bc0d8}

# 15min
jwt.access-token-expiration-ms=${JWT_ACCESS_TOKEN_EXPIRATION_MS:900000}

# 14d
jwt.refresh-token-expiration-ms=${JWT_REFRESH_TOKEN_EXPIRATION_MS:1209600000}
